org.gradle.jvmargs=-Xmx2G

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5

# Mod Properties
mod_version = 2.9.6
maven_group = io.icker
archives_base_name = factions

# Dependencies
fabric_api_version=0.161.0+26.3
lucko_permissions_version=0.7.0
dynmap_api_version=3.7-SNAPSHOT
papi_version=3.2.0+26.3
styled_chat_version=HQ91YnMY
bluemap_api_version=2.7.1
squaremap_api_version=1.2.3
sgui_version=2.2.1+26.3
stapi_version=3.2.0+26.3
flow_version=1.0.3
